name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /ci_cd
          PORT: ${{ secrets.PORT }}
        run: |
          ssh $USER@$HOST << EOF
            set -e

            if [ ! -d "$APP_DIR" ]; then
              mkdir -p "$APP_DIR"
              git clone https://github.com/muhammadaliteacher/xn_3_ci_cd_deploy.git "$APP_DIR"
            fi

            cd "$APP_DIR"

            if [ ! -d .git ]; then
              echo "❌ Repo not cloned properly. Aborting."
              exit 1
            fi

            git pull origin main

            echo "PORT=$PORT" > .env
            npm install
            npm run build

            if pm2 list | grep -q "ci_cd_app"; then
              pm2 restart ci_cd_app
            else
              pm2 start dist/main.js --name ci_cd_app
            fi

            pm2 save
          EOF
